name: Deploy to Render.com
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          password: ${{ secrets.DOCKER_PASSWORD }}
          username: ${{ secrets.DOCKER_USERNAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          logout: true
          push: true
          tags: kttrez/symfi-api:latest

      - name: Deploy to Render.com
        uses: bankfliptech/deploy-to-render@v1
        with:
          apiKey: ${{ secrets.RENDER_API_KEY }}
          deployHookURL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
          serviceId: ${{ secrets.RENDER_SERVICE_ID }}
on:
  - issue_comment
  - pull_request_review_comment
  - push
